# Clippy configuration for Barqly Vault
# Enforces use of tracing for all logging

# Disallow print/debug macros in production code
disallowed-macros = [
    { path = "std::println", reason = "use info! or debug! from tracing instead" },
    { path = "std::eprintln", reason = "use error! or warn! from tracing instead" },
    { path = "std::dbg", reason = "use debug! from tracing instead" },
    { path = "std::print", reason = "use tracing macros instead" },
    { path = "std::eprint", reason = "use tracing macros instead" },
]

# Allow print macros in tests for debugging
allow-print-in-tests = true
allow-dbg-in-tests = true

# Enforce documentation on public items (optional, but good practice)
missing-docs-in-crate-items = true

# Set maximum cognitive complexity
cognitive-complexity-threshold = 30