site_name: Barqly Vault
site_description: Simple, secure file encryption for the Bitcoin ecosystem
site_author: Barqly Team
site_url: https://inauman.github.io/barqly-vault/

# Repository
repo_name: inauman/barqly-vault
repo_url: https://github.com/inauman/barqly-vault
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  # Features
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.prefetch
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  # Custom CSS
  custom_dir: overrides

# Navigation
nav:
  - Home: index.md

# Plugins
plugins:
  - search
  - social

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/inauman/barqly-vault
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/barqlyvault
    - icon: fontawesome/brands/discord
      link: https://discord.gg/barqlyvault

# Copyright
copyright: Copyright &copy; 2024 Barqly Team

# Analytics (optional)
# analytics:
#   provider: google
#   property: !ENV GOOGLE_ANALYTICS_KEY 