name: 'Apple Certificate Manager'
description: 'Setup and cleanup Apple code signing certificates for macOS builds'
author: 'Barqly'

inputs:
  certificate-p12:
    description: 'Base64 encoded P12 certificate'
    required: false
  certificate-password:
    description: 'Certificate password'
    required: false
  operation:
    description: 'Operation to perform: setup or cleanup'
    required: true
    default: 'setup'

outputs:
  keychain-path:
    description: 'Path to the created keychain'
    value: ${{ steps.setup.outputs.keychain-path }}
  certificate-configured:
    description: 'Whether certificate was successfully configured'
    value: ${{ steps.setup.outputs.configured }}

runs:
  using: "composite"
  steps:
    - name: Setup Apple Certificate
      id: setup
      if: inputs.operation == 'setup'
      shell: bash
      env:
        APPLE_CERTIFICATE_P12: ${{ inputs.certificate-p12 }}
        APPLE_CERTIFICATE_PASSWORD: ${{ inputs.certificate-password }}
      run: |
        # Check if certificate is provided
        if [ -z "$APPLE_CERTIFICATE_P12" ]; then
          echo "⚠️ No Apple certificate provided, skipping setup"
          echo "configured=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "🔐 Setting up Apple certificate..."
        
        # Create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        
        # Import certificate from secrets
        echo "$APPLE_CERTIFICATE_P12" | base64 --decode > $CERTIFICATE_PATH
        
        # Create temporary keychain
        security create-keychain -p "$RUNNER_TEMP" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$RUNNER_TEMP" $KEYCHAIN_PATH
        
        # Import certificate to keychain
        security import $CERTIFICATE_PATH -P "$APPLE_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple: -k "$RUNNER_TEMP" $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        
        # Clean up certificate file immediately for security
        rm $CERTIFICATE_PATH
        
        echo "✅ Certificate imported successfully"
        echo "keychain-path=$KEYCHAIN_PATH" >> $GITHUB_OUTPUT
        echo "configured=true" >> $GITHUB_OUTPUT
    
    - name: Cleanup Apple Keychain
      if: inputs.operation == 'cleanup'
      shell: bash
      run: |
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        if [ -f "$KEYCHAIN_PATH" ]; then
          echo "🧹 Cleaning up keychain..."
          security delete-keychain $KEYCHAIN_PATH || true
          echo "✅ Keychain cleaned up"
        else
          echo "ℹ️ No keychain to cleanup"
        fi