name: 'Setup Build Environment'
description: 'Set up Node.js, Rust, and platform-specific dependencies for building Barqly Vault'

inputs:
  rust-target:
    description: 'Rust target triple'
    required: false
  node-version:
    description: 'Node.js version'
    required: false
    default: 'lts/*'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.rust-target }}
        components: rustfmt, clippy
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "./src-tauri -> target"
        key: ${{ runner.os }}-${{ inputs.rust-target }}
    
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          libgtk-3-dev \
          libayatana-appindicator3-dev
    
    - name: Install frontend dependencies
      shell: bash
      run: npm ci