// Deny debug and print macros in production code
#![deny(clippy::print_stdout)]
#![deny(clippy::print_stderr)]
#![deny(clippy::dbg_macro)]
// Allow disallowed macros for this module since Tauri macros may use eprintln internally
#![allow(clippy::disallowed_macros)]

pub mod commands; // Keep public - this is the UI interface
pub mod constants; // Centralized constants for the application
pub mod crypto; // Public for tests, but should be treated as private for external use
pub mod error; // Centralized error handling infrastructure
pub mod file_ops; // Public for tests, but should be treated as private for external use
pub mod logging; // Centralized logging and tracing infrastructure
pub mod models; // Vault and key management models
pub mod prelude;
pub mod services; // Business logic layer (DDD) - renamed from key_management
pub mod storage; // Public for tests, but should be treated as private for external use

use commands::{
    create_manifest,
    decrypt_data,
    delete_key_command,
    encrypt_files,
    encrypt_files_multi,
    // Crypto commands
    get_cache_metrics,
    get_config,
    get_encryption_status,
    get_file_info,
    // Key management commands
    get_key_menu_data,
    get_progress,
    key_management::{
        passphrase::{
            add_passphrase_key_to_vault, generate_key, list_available_passphrase_keys_for_vault,
            list_passphrase_keys_for_vault, validate_passphrase, validate_passphrase_strength,
            validate_vault_passphrase_key, verify_key_passphrase,
        },
        unified_keys::{
            get_vault_keys, list_unified_keys, remove_key_from_vault, test_unified_keys,
            update_key_label,
        },
        yubikey::{
            init_yubikey, init_yubikey_for_vault, list_available_yubikeys_for_vault, list_yubikeys,
            register_yubikey, register_yubikey_for_vault, yubikey_decrypt_file,
            yubikey_list_devices,
        },
    },
    // Storage commands
    list_keys_command,
    select_directory,
    // File commands
    select_files,
    update_config,
    // Vault commands
    vault::{create_vault, delete_vault, get_current_vault, list_vaults, set_current_vault},
    verify_manifest,
};

use crate::prelude::*;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Initialize new tracing system
    if let Err(e) = logging::init() {
        // Use eprintln only for initialization errors
        // This is before logging is set up, so it's acceptable
        #[allow(clippy::disallowed_macros, clippy::print_stderr)]
        {
            eprintln!("Failed to initialize tracing: {e:?}");
        }
    }

    // Use tracing for application started message
    info!("Barqly Vault application started");
}

/// Generate TypeScript bindings for all Tauri commands
/// This is called by the generate-bindings binary and the build hooks
pub fn generate_typescript_bindings() -> Result<(), String> {
    use specta_typescript::Typescript;
    use tauri_specta::{Builder, collect_commands};

    let builder = Builder::<tauri::Wry>::new().commands(collect_commands![
        // Crypto commands
        generate_key,
        validate_passphrase,
        verify_key_passphrase,
        validate_passphrase_strength,
        encrypt_files,
        encrypt_files_multi,
        get_encryption_status,
        decrypt_data,
        verify_manifest,
        get_progress,
        // Storage commands
        list_keys_command,
        delete_key_command,
        // Unified key management
        list_unified_keys,
        test_unified_keys,
        get_vault_keys,
        get_key_menu_data,
        remove_key_from_vault,
        update_key_label,
        get_config,
        update_config,
        get_cache_metrics,
        // File commands
        select_files,
        select_directory,
        get_file_info,
        create_manifest,
        // Vault commands
        create_vault,
        list_vaults,
        get_current_vault,
        set_current_vault,
        delete_vault,
        // Passphrase/YubiKey vault integration
        add_passphrase_key_to_vault,
        list_passphrase_keys_for_vault,
        list_available_passphrase_keys_for_vault,
        validate_vault_passphrase_key,
        init_yubikey_for_vault,
        register_yubikey_for_vault,
        list_available_yubikeys_for_vault,
        // Streamlined YubiKey commands
        list_yubikeys,
        init_yubikey,
        register_yubikey,
        yubikey_list_devices,
        // YubiKey crypto commands
        yubikey_decrypt_file,
    ]);

    builder
        .export(
            Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// This file is auto-generated by tauri-specta. Do not edit manually."),
            "../src-ui/src/bindings.ts",
        )
        .map_err(|e| format!("Failed to export TypeScript bindings: {e}"))
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run_app() {
    // Initialize new tracing system
    if let Err(e) = logging::init() {
        // Use eprintln only for initialization errors
        // This is before logging is set up, so it's acceptable
        #[allow(clippy::disallowed_macros, clippy::print_stderr)]
        {
            eprintln!("Failed to initialize tracing: {e:?}");
        }
    }

    // Use tracing for application started message
    info!("Barqly Vault application started");

    // Build the regular Tauri handler with ALL commands for now (during migration)
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(tauri::generate_handler![
            // Crypto commands
            generate_key,
            validate_passphrase,
            verify_key_passphrase,
            validate_passphrase_strength,
            encrypt_files,
            encrypt_files_multi,
            get_encryption_status,
            decrypt_data,
            verify_manifest,
            get_progress,
            // Storage commands
            list_keys_command,
            delete_key_command,
            // Unified key management
            list_unified_keys,
            test_unified_keys,
            get_vault_keys,
            get_key_menu_data,
            remove_key_from_vault,
            update_key_label,
            get_config,
            update_config,
            get_cache_metrics,
            // File commands
            select_files,
            select_directory,
            get_file_info,
            create_manifest,
            // Vault commands
            create_vault,
            list_vaults,
            get_current_vault,
            set_current_vault,
            delete_vault,
            // Passphrase/YubiKey vault integration
            add_passphrase_key_to_vault,
            list_passphrase_keys_for_vault,
            list_available_passphrase_keys_for_vault,
            validate_vault_passphrase_key,
            init_yubikey_for_vault,
            register_yubikey_for_vault,
            list_available_yubikeys_for_vault,
            // Streamlined YubiKey commands
            list_yubikeys,
            init_yubikey,
            register_yubikey,
            yubikey_list_devices,
            // YubiKey crypto commands
            yubikey_decrypt_file,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
