name: CI Backend

on:
  push:
    paths:
      - 'src-tauri/**'
      - '.github/workflows/ci-backend.yml'
  pull_request:
    paths:
      - 'src-tauri/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies
        run: |
          cd src-tauri
          cargo fetch

      - name: Format check
        run: |
          cd src-tauri
          cargo fmt --all -- --check

      - name: Lint (clippy)
        run: |
          cd src-tauri
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: |
          cd src-tauri
          cargo build --release

      - name: Run tests
        run: |
          cd src-tauri
          cargo test --all 